eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
#  config:
#    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discover:
        location:
          enabled: true
      routes:
        - id: students
          uri: lb://student-service
          predicates:
            - Path=/api/v1/students/**

        - id: schools
          uri: lb://school-service
          predicates:
            - Path=/api/v1/schools/**
